export const MESSAGE_TYPES = {
  CREATE_MESSAGE: 'CREATE_MESSAGE',
  GET_MESSAGE: 'GET_MESSAGE',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',
  UPDATE_READ_STATUS: 'UPDATE_READ_STATUS',
  UPDATE_MESSAGE_READ: 'UPDATE_MESSAGE_READ',
  LOAD_MESSAGE: 'LOAD_MESSAGE',
  FIRST_LOAD: 'FIRST_LOAD'
}